# Frontend Dockerfile - Development
FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy application code
COPY . .

# Expose port
EXPOSE 5000

ENV PORT 5000
ENV HOSTNAME "0.0.0.0"

# Run development server
CMD ["npm", "run", "dev"]

